logging:
  level:
    com:
      global:
        addr: DEBUG

server:
  port: 8081
  servlet:
    context-path: /addr
    
    
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/crm_addr?currentSchema=addr
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: 12345
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: '' 
  h2:
    console:
      enabled: true
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: addr
#  config:
#    import: "optional:configserver:http://localhost:8071/"  
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"  

    
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json 
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.htmlml
    
service:
  title: ${spring.application.name} microservice REST API Documentation(${spring.profiles.active})
  version: v-2
  description: GLOBAL CRM microservice REST API Documentation

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "address"
    description: "Global Address Application"
    version: "1.0.0"       
